version: '3.4'

services:
  src:
    image: ${DOCKER_REGISTRY}collmemaybe/novelgram
    secrets:
      - google
    build:
      context: ../Src
      dockerfile: Dockerfile

secrets:
  google:
    file: ../Src/Secrets/secrets.json
